###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "first_name": "João Vitor",
    "last_name": "Simão",
    "email": "joao3@email.com",
    "recovery_email": "pai@email.com",
    "phone": "(xx) xxxxx-xxxx",
    "password": "123",
    "confirmPassword": "123"
}